# Title of your website
title: 'The Coded Language of Empire'

# Title of your website
subtitle: 'digital history, archival deep-dives, and US imperialism in Cuba’s Third War of Independence'

# Maximum of 150 characters for SEO-purposes.
description: "Digital History, Archival Deep Dives and the Imperial United States in Cuba’s Third War of Independence. AHR History Lab, by Arlene Diaz, Kalani Craig & David Kloster."

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: ''
baseurl: '/AHRDiachronicConversation'

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.url }}{{ site.baseurl }}{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.url }}{{ site.baseurl }}{{ site.urlimg }}image.jpg)
#
urlimg: '/assets/img/'
destination: docs/
permalink:   /:categories/:title/

year : 2022
markdown : kramdown
exclude :
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md

#plugins:
#  - jekyll-seo-tag

google_analytics_tracking_id: UA-11680223-1
google_g4_analytics_id: G-LVREG1Y1DT

